version: '3'

services:

  dash_app:
    container_name: insectt_dash
    restart: always
    build: ./dash_app
    ports:
      - "9123:9123"


  nginx:
    container_name: insectt_nginx
    restart: always
    build: ./nginx
    ports:
      - "9122:9122"
    depends_on:
      - dash_app